ports:
- port: 8000
tasks:
- init: |
    python3 -m venv .venv
    source .venv/bin/activate
    pip3 install -r requirements.txt

    npm install
  command: |
    source .venv/bin/activate
    mkdocs serve
